version: '3'

services:

  coordinator-1:
    # build: './kafka_server/coordinator/' # use for local build
    image: mahdigheidi/sad-coordinator # on production server
    platform: linux/arm64
    ports:
      - '5003:5000'
    networks:
      - broker

  coordinator-2:
    # build: './kafka_server/coordinator/'
    image: mahdigheidi/sad-coordinator # on production server
    ports:
      - '5004:5000'
    networks:
      - broker

  broker-1:
    # build: './kafka_server/broker/'
    image: mahdigheidi/sad-broker # on production server
    ports:
      - '5678:5003'
    networks:
      - broker

  broker-2:
    # build: './kafka_server/broker/'
    image: mahdigheidi/sad-broker # on production server
    ports:
      - '5679:5003'
    networks:
      - broker

  broker-3:
    # build: './kafka_server/broker/'
    image: mahdigheidi/sad-broker # on production server
    ports:
      - '5680:5003'
    networks:
      - broker

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - broker

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - broker

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - broker

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  broker:
    driver: bridge
