version: '3'

services:

  coordinator:
    build: './kafka_server/coordinator/'
    ports:
      - '5003:5000'

  broker-1:
    build: './kafka_server/broker/'
    ports:
      - '5678:5003'
  broker-2:
    build: './kafka_server/broker/'
    ports:
      - '5679:5003'
  broker-3:
    build: './kafka_server/broker/'
    ports:
      - '5680:5003'

  prometheus:
    image: prom/prometheus:latest
    command:
      - --storage.tsdb.retention.time=7d
      - --config.file=/etc/prometheus/prometheus.yml
      # - --storage.tsdb.retention.size=10GB
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana-provisioning/datasources:/etc/grafana/provisioning/datasources

  node_exporter_1:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  node_exporter_2: 
    image: prom/node-exporter:latest
    ports:
      - "9101:9100"
