version: '3'
services:
  app:
    image: openjdk:17-jdk-slim
    ports:
      - "8081:8081"
    volumes:
      - ./target:/app
    working_dir: /src
    command: ["java", "-jar", "broker-0.0.1-SNAPSHOT.jar"]
