scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'broker'
    scrape_interval: 5s
    static_configs:
      - targets: ['broker-1:5003', 'broker-2:5003', 'broker-3:5003']
  - job_name: 'coordinator'
    scrape_interval: 5s
    static_configs:
      - targets: ['coordinator-1:5000', 'coordinator-2:5000']
