scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter_1:9100', 'node_exporter_2:9100']
  - job_name: 'broker'
    scrape_interval: 5s
    static_configs:
      - targets: ['broker-1:5003', 'broker-2:5003', 'broker-3:5003']
  - job_name: 'coordinator'
    scrape_interval: 5s
    static_configs:
      - targets: ['coordinator:5000']