CLIENT_DATABASE_FILE_PATH = "client_database.json"
BROKER_DATABASE_FILE_PATH = "broker_database.json"
BROKER_REPLICA_FILE_PATH = "broker_replicas.json"
SUBSCRIBER_DATABASE_FILE_PATH = "subscriber_database.json"
CLIENT_HEARTBEAT_DATABASE_FILE_PATH = "client_heartbeat.json"
BROKER_HEARTBEAT_DATABASE_FILE_PATH = "broker_heartbeat.json"
