name: sad-server-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-push-broker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./kafka_server/broker/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mahdigheidi/sad-broker:latest


  build-and-push-coordinator:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./kafka_server/coordinator/
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          push: true
          tags: mahdigheidi/sad-coordinator:latest

  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint 
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        pytest

  static-code-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install bandit
        run: |
          pip install bandit

      - name: Run bandit
        run: |
          bandit -r .

  
  deploy-prod-broker:
    name: Deploy Broker to Production
    runs-on: ubuntu-latest
    needs: build-push-broker


    steps:
      - name: Deploy to production
        run: |
          # Here you can add your deployment commands/scripts
          # For example:
          ssh user@your-production-server 'docker pull mahdigheidi/sad-broker:latest && docker-compose up -d'

  deploy-prod-coordinator:
    name: Deploy Coordinator to Production
    runs-on: ubuntu-latest
    needs: build-push-coordinator

    steps:
      - name: Deploy to production
        run: |
          # Here you can add your deployment commands/scripts
          # For example:
          ssh user@your-production-server 'docker pull ghcr.io/your-github-username/your-repo-name:latest && docker-compose up -d'
